from typing import Any, Dict


class Advisor:
    """
    AI Advisor (Explainability Layer)

    HARD RULES:
    - Read-only
    - No mutation
    - No DB access
    - No policy logic
    - No guessing resource IDs
    - Uses ONLY provided finding fields
    """

    def advise(self, finding: Dict[str, Any]) -> Dict[str, Any]:
        """
        Input:
          finding dict (from FindingStore.to_dict)

        Output:
          explanation payload safe for frontend display
        """

        policy_id = finding.get("policy_id")
        severity = finding.get("severity")
        resource_type = finding.get("resource_type")
        resource_id = finding.get("resource_id")
        region = finding.get("region")
        status = finding.get("status")

        risk_score = finding.get("risk_score")
        risk_bucket = finding.get("risk_bucket")
        score_explain = finding.get("score_explain", {})

        evidence = finding.get("evidence") or {}

        return {
            "summary": self._summary(policy_id, resource_type, resource_id, severity),
            "risk_assessment": self._risk_section(risk_score, risk_bucket, score_explain),
            "attack_narrative": self._attack_narrative(policy_id, resource_type, evidence),
            "impact": self._impact(policy_id, resource_type),
            "recommended_action": self._recommendation(policy_id),
            "metadata": {
                "policy_id": policy_id,
                "resource_type": resource_type,
                "resource_id": resource_id,
                "region": region,
                "status": status,
            },
        }

    # -------------------------
    # Sections
    # -------------------------

    def _summary(
        self,
        policy_id: str,
        resource_type: str,
        resource_id: str,
        severity: str,
    ) -> str:
        return (
            f"This finding was generated by policy {policy_id} and affects a "
            f"{resource_type} resource ({resource_id}). "
            f"The issue is classified as {severity} severity."
        )

    def _risk_section(
        self,
        score: int,
        bucket: str,
        explain: Dict[str, Any],
    ) -> Dict[str, Any]:
        return {
            "score": score,
            "bucket": bucket,
            "explanation": explain,
        }

    def _attack_narrative(
        self,
        policy_id: str,
        resource_type: str,
        evidence: Dict[str, Any],
    ) -> str:
        """
        Narrative is policy-aware but NOT speculative.
        Only describes what the evidence already proves.
        """

        if policy_id == "POL-001":
            return (
                "The EC2 instance has a public IP address and is associated with "
                "a security group rule that allows inbound SSH (port 22) access "
                "from 0.0.0.0/0. This allows any external actor on the internet "
                "to attempt direct SSH connections to the instance."
            )

        if policy_id == "POL-004":
            return (
                "The security group allows unrestricted inbound traffic on one "
                "or more ports. This increases exposure to unauthorized access "
                "and network-based attacks."
            )

        if policy_id in ("POL-005", "POL-006", "POL-007"):
            return (
                "The S3 bucket configuration allows public access through "
                "bucket policies or ACL settings. This makes stored objects "
                "accessible beyond intended boundaries."
            )

        if policy_id in ("POL-008", "POL-010", "POL-011"):
            return (
                "The IAM configuration grants elevated or administrative "
                "permissions. If misused or compromised, this could lead to "
                "full account-level impact."
            )

        if policy_id == "POL-012":
            return (
                "CloudTrail logging is missing or misconfigured, reducing "
                "visibility into account activity and limiting incident "
                "detection and investigation."
            )

        return (
            "This finding represents a security condition detected by policy "
            f"{policy_id} based on the current configuration and evidence."
        )

    def _impact(self, policy_id: str, resource_type: str) -> str:
        if policy_id in ("POL-001", "POL-002", "POL-003", "POL-004"):
            return (
                "Publicly exposed infrastructure increases the risk of "
                "unauthorized access, brute-force attempts, and exploitation "
                "of unpatched services."
            )

        if policy_id in ("POL-005", "POL-006", "POL-007"):
            return (
                "Public storage exposure may result in data leakage, compliance "
                "violations, and unintended data distribution."
            )

        if policy_id in ("POL-008", "POL-010", "POL-011"):
            return (
                "Excessive IAM permissions can allow attackers to escalate "
                "privileges and compromise additional resources."
            )

        if policy_id == "POL-012":
            return (
                "Lack of audit logging reduces the ability to detect breaches "
                "and respond effectively to security incidents."
            )

        return (
            "If left unaddressed, this issue may increase the overall security "
            "risk of the environment."
        )

    def _recommendation(self, policy_id: str) -> str:
        """
        High-level guidance only.
        Detailed remediation already exists elsewhere.
        """

        if policy_id == "POL-001":
            return (
                "Restrict SSH access by limiting inbound rules to trusted IP "
                "ranges or remove public SSH access entirely."
            )

        if policy_id == "POL-004":
            return "Review security group rules and remove overly permissive " "inbound access."

        if policy_id in ("POL-005", "POL-006", "POL-007"):
            return (
                "Disable public access on the S3 bucket and enforce least-"
                "privilege access controls."
            )

        if policy_id in ("POL-008", "POL-010", "POL-011"):
            return (
                "Reduce IAM permissions to the minimum required and remove "
                "unused or overly privileged identities."
            )

        if policy_id == "POL-012":
            return (
                "Enable and properly configure CloudTrail to ensure full "
                "account activity logging."
            )

        return "Review the affected resource configuration and apply security " "best practices."
