"""initial schema

Revision ID: 45f883d34191
Revises:
Create Date: 2026-02-22 16:58:11.902381

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45f883d34191"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=128), nullable=False),
        sa.Column("asset_type", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_asset_id"), "assets", ["asset_id"], unique=False)
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("asset_count", sa.Integer(), nullable=True),
        sa.Column("finding_count", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_reason", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_runs_scan_id"), "scan_runs", ["scan_id"], unique=True)
    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("resource_id", sa.String(length=256), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("asset_id_fk", sa.Integer(), nullable=False),
        sa.Column("scan_run_id", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("remediation", sa.String(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id_fk"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "resource_id", name="uq_finding_policy_resource"),
    )
    op.create_index(op.f("ix_findings_policy_id"), "findings", ["policy_id"], unique=False)
    op.create_index(op.f("ix_findings_region"), "findings", ["region"], unique=False)
    op.create_index(op.f("ix_findings_resource_id"), "findings", ["resource_id"], unique=False)
    op.create_index(op.f("ix_findings_resource_type"), "findings", ["resource_type"], unique=False)
    op.create_table(
        "finding_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_events")
    op.drop_index(op.f("ix_findings_resource_type"), table_name="findings")
    op.drop_index(op.f("ix_findings_resource_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_region"), table_name="findings")
    op.drop_index(op.f("ix_findings_policy_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_scan_runs_scan_id"), table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_index(op.f("ix_assets_asset_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
