"""baseline schema

Revision ID: 4e3879a1cf3a
Revises:
Create Date: 2026-01-28 17:25:23.226279

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4e3879a1cf3a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
