"""add resource fields to findings

Revision ID: a63dac2c432c
Revises: 4e3879a1cf3a
Create Date: 2026-01-28 18:00:34.821553

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a63dac2c432c"
down_revision: Union[str, None] = "4e3879a1cf3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("finding_events", sa.Column("snapshot", sa.JSON(), nullable=True))
    op.add_column("findings", sa.Column("resource_id", sa.String(length=256), nullable=False))
    op.add_column("findings", sa.Column("resource_type", sa.String(length=64), nullable=False))
    op.add_column("findings", sa.Column("region", sa.String(length=32), nullable=False))
    op.create_index(op.f("ix_findings_region"), "findings", ["region"], unique=False)
    op.create_index(op.f("ix_findings_resource_id"), "findings", ["resource_id"], unique=False)
    op.create_index(op.f("ix_findings_resource_type"), "findings", ["resource_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_findings_resource_type"), table_name="findings")
    op.drop_index(op.f("ix_findings_resource_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_region"), table_name="findings")
    op.drop_column("findings", "region")
    op.drop_column("findings", "resource_type")
    op.drop_column("findings", "resource_id")
    op.drop_column("finding_events", "snapshot")
    # ### end Alembic commands ###
